---
title: es6系列-Async
date: 2020-07-10 18:07:49
tags:
  - 日积月累
  - es6

---

[Noney Li]: https://github.com/noney/ "noneyli"

*—— 同时发表于[coding](http://0kv30q.coding-pages.com/)*

__作者：[Noney Li]__

#### 写在前面

`async/await`是终极异步解决方案。

#### 关键字async

`async`放在函数定义前面，说明这个函数里面会有异步操作，函数的返回值是一个`Promise`对象，`return`语句返回值，会成为`then`函数的参数。

- 当`return`一个原始值时，函数会通过`Promise.resolve()`方法，将它变成一个`Promise`对象

```javascript
async function pro() {
  return '结果为: 1';
}

pro()
  .then((res) => {
    console.log(res);
  })
//结果为: 1
//等价于
let pro = Promise.resolve('结果为: 1');

pro
  .then((res) => {
    console.log(res)
  })
```

<!-- more -->

- 当`return`一个`Promise`时，直接返回

```javascript
async function pro() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('结果为: 1');
    }, 1000)  
  })
}

pro()
  .then((res) => {
    console.log(res);
  })
//结果为: 1
```

- 函数内部执行出现错误时，返回`Promise`实例状态为`失败`，会执行它的`catch`方法

```javascript
async function pro() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject('出错了');
    }, 1000)  
  })
}

pro()
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  })
```

#### 关键字await

```javascript
console.log(`同步1`);
async function pro() {
  console.log(`等待1`);
  await 1;
  console.log(`等待2`)
  await new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log(`等待2完成`);
      resolve();
    }, 1000)
  });
  console.log(`等待3`)
}
console.log(`同步2`)
pro()
  .then((res) => {
    console.log(`回调`);
  })
  .catch((err) => {
    console.log(4);
  })
console.log(`同步3`)
//同步1
//同步2
//等待1
//同步3
//等待2
//等待2完成
//等待3
//回调
```

从上面例子我们可以看出`await`做了什么

- 遇到`await`程序会立即返回执行`同步`代码，函数暂停
- `await`后面是`原始值`时，直接获取返回值为`原始值`
- `await`后面是`Promise`时，会等待执行完成，获取返回值
- 函数体内所有执行结束，才会执行`then`函数（除非遇到`return`或者抛出错误）

`await`后面产生的`reject`会被`catch`接收，前面是否有`return`效果一样

```javascript
async function pro() {
  await Promise.reject('出错了~');
}

pro()
  .then(() => {

  })
  .catch((err) => {
    console.log(err);
  })
//出错了
```

当`await`抛出错误，后面的不会再执行

```javascript
async function pro() {
  await Promise.reject('出错了~');
  return await Promise.resolve('结果为: 1');
}

pro()
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  })
//出错了
```

#### 错误处理

`await`抛出错误，会执行返回`Promise`的`catch`函数。防止出错的方式有两种

- 将`await`放在`try...catch`体内（错误在里面被捕获处理了，如果有多个`await`命令，可以统一放在`try...catch`结构中）

```javascript
async function pro() {
  try {
    await Promise.reject('出错了~');
  } catch(e) {
    console.log(e);
  }
  return await Promise.resolve('结果为: 1');
}

pro()
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  })
//出错了~
//结果为: 1
```

- `await`后面的异步调用，接自己的`catch`（错误被后面`catch`捕获，返回新的`Promise`状态为`成功`）

```javascript
async function pro() {
  await Promise.reject('出错了~').catch((e) => console.log(e));
  return await Promise.resolve('结果为: 1');
}

pro()
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  })
//出错了~
//结果为: 1
```

#### 继发&并发

`继发`是执行完前面的，才会继续执行，适用于有前后依赖关系的逻辑

```javascript
function pro() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('结果为: 1');
    }, 1000)
  })
}

function pro1() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('结果为: 2');
    }, 1000)
  })
}

async function active() {
  console.time('耗时');
  let res = await pro();
  let res1 = await pro1();
  console.timeEnd('耗时');
  return `${res} ${res1}`;
}
async function active1() {
  console.time('耗时');
  let res = [];
  for(let v of [0, 1]) {
    res.push(await obj[`pro${v}`]());
  }
  console.timeEnd('耗时');
  return `${res[0]} ${res[1]}`;
}

active()
  .then((res) => {
    console.log(res);
  })
//耗时: 2009.088ms
//结果为: 1 结果为: 2
active1()
  .then((res) => {
    console.log(res);
  })
//耗时: 2005.423ms
//结果为: 1 结果为: 2
```

`并发`是表示同时触发，适用于没有依赖关系的逻辑

```javascript
function pro() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('结果为: 1');
    }, 1000)
  })
}

function pro1() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('结果为: 2');
    }, 1000)
  })
}
//方式一
async function active() {
  console.time('耗时');
  let [res, res1] = await Promise.all([pro(), pro1()])
  console.timeEnd('耗时');
  return `${res} ${res1}`;
}
//方式二
async function active1() {
  console.time('耗时');
  let res = pro();
  let res1 = pro1();
  let r = await res;
  let r1 = await res1;
  console.timeEnd('耗时');
  return `${r} ${r1}`;
}
//方式三
async function active2() {
  console.time('耗时');
  let res = await new Promise((resolve, reject) => {
    let index = 0,
      r = [];
    [0, 1].forEach(async function (v, k) {
      console.log(`同步`);
      r.push(await obj[`pro${v}`]());
      console.log(`回调`);
      if (k == 1) {
        console.log(`完成`);
        resolve(r);
      }
      });
  })
  console.timeEnd('耗时');
  return `${res[0]} ${res[1]}`;
}
//方式四
async function active4() {
  console.time('耗时');
  let docs = [{}, {}];
  let promises = docs.map((v, k) => obj[`pro${k}`]());
  let res = [];

  for (let promise of promises) {
    res.push(await promise);
  }
  console.timeEnd('耗时');
  return `${res[0]} ${res[1]}`;
}

active()
  .then((res) => {
    console.log(res);
  })
//耗时: 1007.115ms
//结果为: 1 结果为: 2
active1()
  .then((res) => {
    console.log(res);
  })
//耗时: 1001.871ms
//结果为: 1 结果为: 2
active2()
  .then((res) => {
    console.log(res);
  })
//同步
//同步
//回调
//回调
//完成
//耗时: 1010.006ms
//结果为: 1 结果为: 2
active4()
  .then((res) => {
    console.log(res);
  })
//耗时: 1003.080ms
//结果为: 1 结果为: 2
```

`并发`&`继发`执行解析

```javascript
let obj = {
  pro0() {
    console.log('pro0开始');
    return new Promise((resolve, reject) => {
      console.log('pro0异步开始')
      setTimeout(() => {
        console.log('pro0异步完成');
        resolve('结果为: 1');
      }, 1000)
    })
  },
  pro1() {
    console.log('pro1开始');
    return new Promise((resolve, reject) => {
      console.log('pro1异步开始')
      setTimeout(() => {
        console.log('pro1异步完成');
        resolve('结果为: 2');
      }, 1000)
    })
  }
}
// 继发
async function jf() {
  console.time('耗时:')
  console.log(`等待pro0结果`)
  let res = await obj.pro0();
  console.log(`等待pro1结果`)
  let res1 = await obj.pro1();
  console.log('所有执行完成')
  console.timeEnd('耗时:')
  return `${res} ${res1}`;
}

async function bf() {
  console.time('耗时:')
  let res = obj.pro0();
  let res1 = obj.pro1();
  console.log(`等待pro0结果`)
  let r = await res;
  console.log(`等待pro1结果`)
  let r1 = await res1;
  console.log('所有执行完成')
  console.timeEnd('耗时:')
  return `${r} ${r1}`;
}

bf()
  .then((res) => {
    console.log(`回调完成`);
    console.log(res);
  })
//pro0开始
//pro0异步开始
//pro1开始
//pro1异步开始
//等待pro0结果
//pro0异步完成
//等待pro1结果
//pro1异步完成
//所有执行完成
//耗时:: 1013.000ms
//回调完成
//结果为: 1 结果为: 2

// 从输出我们可以看出，我们执行`pro0、pro1`函数的时候，异步已经开始并发执行了，下面的`await`只是等待拿到执行结果

jf()
  .then((res) => {
    console.log(`回调完成`);
    console.log(res);
  })

//等待pro0结果
//pro0开始
//pro0异步开始
//pro0异步完成
//等待pro1结果
//pro1开始
//pro1异步开始
//pro1异步完成
//所有执行完成
//耗时:: 2010.812ms
//回调完成
//结果为: 1 结果为: 2

// 从输出我们可以看出，`pro1`是等待`pro0`完成执行完成才会执行
```

#### 参考

[async 函数](https://es6.ruanyifeng.com/#docs/async)